### ISSUE TITLE
TFT Bulk Tool: Character name should ignore markdown

### ISSUE THREAD

**Issue by hmcgonig** [PoeStack/issues#59]
I've personally seen this a few times this league - the discord bot that posts TFT bulk sell messages does not escape markdown found in IGNs. 

I own a few single word names in game (for the sake of an example `Word`), and multiple times this league someone with the name  `_Word_` has tried to post a trade using the bulk sell tool, which discord renders as markdown in italics ie. _Word_. So when a buyer attempts to contact the seller, the whisper message does not include the `_` in the character name. This results in me getting spammed for a trade that someone else has posted. I practically have a keybound response to these people at this point because its happened at least once every couple days to me.

**Comment by hmcgonig** [comment]
I think you could just surround the IGN with backticks to put it in a discord code block and that should properly escape the markdown.

**Comment by Jzir** [comment]
Fixed via https://github.com/PoeStack/poestack-apollo/pull/2
