### ISSUE TITLE
Site is stuck on infinite loading

### ISSUE THREAD

**Issue by kamiatus1** [PoeStack/issues#60]
Connecting PoE account does nothing. Using different browsers does nothing.

**Comment by MarcelHofherr** [comment]
Can confirm. I authorize the site to use my PoE Data and yet after redirect it still says "Connect PoE Account". Though this could also be an issue on GGG's side.

**Comment by imtheone-ux** [comment]
Same thing trying different browser even vpn nothign seems to work!

**Comment by Nox1789** [comment]
Same issue, login via poe and/or discord doesn't work

**Comment by Jzir** [comment]
All of the above comments were posted during a time of intense load - recent improvements have been made and performance is continuing to be worked on.
